// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.li.proto;

public final class MessageProto {
    private MessageProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface MessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Message)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 消息头
         * </pre>
         *
         * <code>.Header header = 1;</code>
         */
        boolean hasHeader();

        /**
         * <pre>
         * 消息头
         * </pre>
         *
         * <code>.Header header = 1;</code>
         */
        Header getHeader();

        /**
         * <pre>
         * 消息头
         * </pre>
         *
         * <code>.Header header = 1;</code>
         */
        HeaderOrBuilder getHeaderOrBuilder();

        /**
         * <pre>
         * 消息体
         * </pre>
         *
         * <code>bytes body = 2;</code>
         */
        com.google.protobuf.ByteString getBody();
    }

    /**
     * Protobuf type {@code Message}
     */
    public static final class Message extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Message)
            MessageOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Message.newBuilder() to construct.
        private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Message() {
            body_ = com.google.protobuf.ByteString.EMPTY;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Message(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            Header.Builder subBuilder = null;
                            if (header_ != null) {
                                subBuilder = header_.toBuilder();
                            }
                            header_ = input.readMessage(Header.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(header_);
                                header_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 18: {

                            body_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MessageProto.internal_static_Message_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MessageProto.internal_static_Message_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Message.class, Builder.class);
        }

        public static final int HEADER_FIELD_NUMBER = 1;
        private Header header_;

        /**
         * <pre>
         * 消息头
         * </pre>
         *
         * <code>.Header header = 1;</code>
         */
        public boolean hasHeader() {
            return header_ != null;
        }

        /**
         * <pre>
         * 消息头
         * </pre>
         *
         * <code>.Header header = 1;</code>
         */
        public Header getHeader() {
            return header_ == null ? Header.getDefaultInstance() : header_;
        }

        /**
         * <pre>
         * 消息头
         * </pre>
         *
         * <code>.Header header = 1;</code>
         */
        public HeaderOrBuilder getHeaderOrBuilder() {
            return getHeader();
        }

        public static final int BODY_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString body_;

        /**
         * <pre>
         * 消息体
         * </pre>
         *
         * <code>bytes body = 2;</code>
         */
        public com.google.protobuf.ByteString getBody() {
            return body_;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (header_ != null) {
                output.writeMessage(1, getHeader());
            }
            if (!body_.isEmpty()) {
                output.writeBytes(2, body_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (header_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getHeader());
            }
            if (!body_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, body_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Message)) {
                return super.equals(obj);
            }
            Message other = (Message) obj;

            boolean result = true;
            result = result && (hasHeader() == other.hasHeader());
            if (hasHeader()) {
                result = result && getHeader()
                        .equals(other.getHeader());
            }
            result = result && getBody()
                    .equals(other.getBody());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasHeader()) {
                hash = (37 * hash) + HEADER_FIELD_NUMBER;
                hash = (53 * hash) + getHeader().hashCode();
            }
            hash = (37 * hash) + BODY_FIELD_NUMBER;
            hash = (53 * hash) + getBody().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Message parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Message parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Message parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Message parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Message parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Message parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Message parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Message parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Message parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Message parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Message parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Message parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Message prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Message}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Message)
                MessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return MessageProto.internal_static_Message_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return MessageProto.internal_static_Message_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Message.class, Builder.class);
            }

            // Construct using com.li.proto.MessageProto.Message.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                if (headerBuilder_ == null) {
                    header_ = null;
                } else {
                    header_ = null;
                    headerBuilder_ = null;
                }
                body_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return MessageProto.internal_static_Message_descriptor;
            }

            @Override
            public Message getDefaultInstanceForType() {
                return Message.getDefaultInstance();
            }

            @Override
            public Message build() {
                Message result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public Message buildPartial() {
                Message result = new Message(this);
                if (headerBuilder_ == null) {
                    result.header_ = header_;
                } else {
                    result.header_ = headerBuilder_.build();
                }
                result.body_ = body_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Message) {
                    return mergeFrom((Message) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Message other) {
                if (other == Message.getDefaultInstance()) return this;
                if (other.hasHeader()) {
                    mergeHeader(other.getHeader());
                }
                if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
                    setBody(other.getBody());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Message parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Message) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private Header header_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    Header, Header.Builder, HeaderOrBuilder> headerBuilder_;

            /**
             * <pre>
             * 消息头
             * </pre>
             *
             * <code>.Header header = 1;</code>
             */
            public boolean hasHeader() {
                return headerBuilder_ != null || header_ != null;
            }

            /**
             * <pre>
             * 消息头
             * </pre>
             *
             * <code>.Header header = 1;</code>
             */
            public Header getHeader() {
                if (headerBuilder_ == null) {
                    return header_ == null ? Header.getDefaultInstance() : header_;
                } else {
                    return headerBuilder_.getMessage();
                }
            }

            /**
             * <pre>
             * 消息头
             * </pre>
             *
             * <code>.Header header = 1;</code>
             */
            public Builder setHeader(Header value) {
                if (headerBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    header_ = value;
                    onChanged();
                } else {
                    headerBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <pre>
             * 消息头
             * </pre>
             *
             * <code>.Header header = 1;</code>
             */
            public Builder setHeader(
                    Header.Builder builderForValue) {
                if (headerBuilder_ == null) {
                    header_ = builderForValue.build();
                    onChanged();
                } else {
                    headerBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <pre>
             * 消息头
             * </pre>
             *
             * <code>.Header header = 1;</code>
             */
            public Builder mergeHeader(Header value) {
                if (headerBuilder_ == null) {
                    if (header_ != null) {
                        header_ =
                                Header.newBuilder(header_).mergeFrom(value).buildPartial();
                    } else {
                        header_ = value;
                    }
                    onChanged();
                } else {
                    headerBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <pre>
             * 消息头
             * </pre>
             *
             * <code>.Header header = 1;</code>
             */
            public Builder clearHeader() {
                if (headerBuilder_ == null) {
                    header_ = null;
                    onChanged();
                } else {
                    header_ = null;
                    headerBuilder_ = null;
                }

                return this;
            }

            /**
             * <pre>
             * 消息头
             * </pre>
             *
             * <code>.Header header = 1;</code>
             */
            public Header.Builder getHeaderBuilder() {

                onChanged();
                return getHeaderFieldBuilder().getBuilder();
            }

            /**
             * <pre>
             * 消息头
             * </pre>
             *
             * <code>.Header header = 1;</code>
             */
            public HeaderOrBuilder getHeaderOrBuilder() {
                if (headerBuilder_ != null) {
                    return headerBuilder_.getMessageOrBuilder();
                } else {
                    return header_ == null ?
                            Header.getDefaultInstance() : header_;
                }
            }

            /**
             * <pre>
             * 消息头
             * </pre>
             *
             * <code>.Header header = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    Header, Header.Builder, HeaderOrBuilder>
            getHeaderFieldBuilder() {
                if (headerBuilder_ == null) {
                    headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            Header, Header.Builder, HeaderOrBuilder>(
                            getHeader(),
                            getParentForChildren(),
                            isClean());
                    header_ = null;
                }
                return headerBuilder_;
            }

            private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <pre>
             * 消息体
             * </pre>
             *
             * <code>bytes body = 2;</code>
             */
            public com.google.protobuf.ByteString getBody() {
                return body_;
            }

            /**
             * <pre>
             * 消息体
             * </pre>
             *
             * <code>bytes body = 2;</code>
             */
            public Builder setBody(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                body_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息体
             * </pre>
             *
             * <code>bytes body = 2;</code>
             */
            public Builder clearBody() {

                body_ = getDefaultInstance().getBody();
                onChanged();
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Message)
        }

        // @@protoc_insertion_point(class_scope:Message)
        private static final Message DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Message();
        }

        public static Message getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Message>
                PARSER = new com.google.protobuf.AbstractParser<Message>() {
            @Override
            public Message parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Message(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Message> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Message> getParserForType() {
            return PARSER;
        }

        @Override
        public Message getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface HeaderOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Header)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 校验码
         * </pre>
         *
         * <code>int32 crcCode = 1;</code>
         */
        int getCrcCode();

        /**
         * <pre>
         * 消息长度(包括消息头和消息体)
         * </pre>
         *
         * <code>int32 length = 2;</code>
         */
        int getLength();

        /**
         * <pre>
         * sessionId
         * </pre>
         *
         * <code>int64 sessionId = 3;</code>
         */
        long getSessionId();

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>int32 type = 4;</code>
         */
        int getType();

        /**
         * <pre>
         * 消息优先级
         * </pre>
         *
         * <code>int32 priority = 5;</code>
         */
        int getPriority();

        /**
         * <pre>
         * 可选字段,用于扩展消息头
         * </pre>
         *
         * <code>map&lt;string, bytes&gt; attachment = 6;</code>
         */
        int getAttachmentCount();

        /**
         * <pre>
         * 可选字段,用于扩展消息头
         * </pre>
         *
         * <code>map&lt;string, bytes&gt; attachment = 6;</code>
         */
        boolean containsAttachment(
                String key);

        /**
         * Use {@link #getAttachmentMap()} instead.
         */
        @Deprecated
        java.util.Map<String, com.google.protobuf.ByteString>
        getAttachment();

        /**
         * <pre>
         * 可选字段,用于扩展消息头
         * </pre>
         *
         * <code>map&lt;string, bytes&gt; attachment = 6;</code>
         */
        java.util.Map<String, com.google.protobuf.ByteString>
        getAttachmentMap();

        /**
         * <pre>
         * 可选字段,用于扩展消息头
         * </pre>
         *
         * <code>map&lt;string, bytes&gt; attachment = 6;</code>
         */

        com.google.protobuf.ByteString getAttachmentOrDefault(
                String key,
                com.google.protobuf.ByteString defaultValue);

        /**
         * <pre>
         * 可选字段,用于扩展消息头
         * </pre>
         *
         * <code>map&lt;string, bytes&gt; attachment = 6;</code>
         */

        com.google.protobuf.ByteString getAttachmentOrThrow(
                String key);
    }

    /**
     * Protobuf type {@code Header}
     */
    public static final class Header extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Header)
            HeaderOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Header.newBuilder() to construct.
        private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Header() {
            crcCode_ = 0;
            length_ = 0;
            sessionId_ = 0L;
            type_ = 0;
            priority_ = 0;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Header(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            crcCode_ = input.readInt32();
                            break;
                        }
                        case 16: {

                            length_ = input.readInt32();
                            break;
                        }
                        case 24: {

                            sessionId_ = input.readInt64();
                            break;
                        }
                        case 32: {

                            type_ = input.readInt32();
                            break;
                        }
                        case 40: {

                            priority_ = input.readInt32();
                            break;
                        }
                        case 50: {
                            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                                attachment_ = com.google.protobuf.MapField.newMapField(
                                        AttachmentDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000020;
                            }
                            com.google.protobuf.MapEntry<String, com.google.protobuf.ByteString>
                                    attachment__ = input.readMessage(
                                    AttachmentDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            attachment_.getMutableMap().put(
                                    attachment__.getKey(), attachment__.getValue());
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MessageProto.internal_static_Header_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        @Override
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 6:
                    return internalGetAttachment();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MessageProto.internal_static_Header_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Header.class, Builder.class);
        }

        private int bitField0_;
        public static final int CRCCODE_FIELD_NUMBER = 1;
        private int crcCode_;

        /**
         * <pre>
         * 校验码
         * </pre>
         *
         * <code>int32 crcCode = 1;</code>
         */
        public int getCrcCode() {
            return crcCode_;
        }

        public static final int LENGTH_FIELD_NUMBER = 2;
        private int length_;

        /**
         * <pre>
         * 消息长度(包括消息头和消息体)
         * </pre>
         *
         * <code>int32 length = 2;</code>
         */
        public int getLength() {
            return length_;
        }

        public static final int SESSIONID_FIELD_NUMBER = 3;
        private long sessionId_;

        /**
         * <pre>
         * sessionId
         * </pre>
         *
         * <code>int64 sessionId = 3;</code>
         */
        public long getSessionId() {
            return sessionId_;
        }

        public static final int TYPE_FIELD_NUMBER = 4;
        private int type_;

        /**
         * <pre>
         * 消息类型
         * </pre>
         *
         * <code>int32 type = 4;</code>
         */
        public int getType() {
            return type_;
        }

        public static final int PRIORITY_FIELD_NUMBER = 5;
        private int priority_;

        /**
         * <pre>
         * 消息优先级
         * </pre>
         *
         * <code>int32 priority = 5;</code>
         */
        public int getPriority() {
            return priority_;
        }

        public static final int ATTACHMENT_FIELD_NUMBER = 6;

        private static final class AttachmentDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    String, com.google.protobuf.ByteString> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<String, com.google.protobuf.ByteString>newDefaultInstance(
                                    MessageProto.internal_static_Header_AttachmentEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.BYTES,
                                    com.google.protobuf.ByteString.EMPTY);
        }

        private com.google.protobuf.MapField<
                String, com.google.protobuf.ByteString> attachment_;

        private com.google.protobuf.MapField<String, com.google.protobuf.ByteString>
        internalGetAttachment() {
            if (attachment_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        AttachmentDefaultEntryHolder.defaultEntry);
            }
            return attachment_;
        }

        public int getAttachmentCount() {
            return internalGetAttachment().getMap().size();
        }

        /**
         * <pre>
         * 可选字段,用于扩展消息头
         * </pre>
         *
         * <code>map&lt;string, bytes&gt; attachment = 6;</code>
         */

        public boolean containsAttachment(
                String key) {
            if (key == null) {
                throw new NullPointerException();
            }
            return internalGetAttachment().getMap().containsKey(key);
        }

        /**
         * Use {@link #getAttachmentMap()} instead.
         */
        @Deprecated
        public java.util.Map<String, com.google.protobuf.ByteString> getAttachment() {
            return getAttachmentMap();
        }

        /**
         * <pre>
         * 可选字段,用于扩展消息头
         * </pre>
         *
         * <code>map&lt;string, bytes&gt; attachment = 6;</code>
         */

        public java.util.Map<String, com.google.protobuf.ByteString> getAttachmentMap() {
            return internalGetAttachment().getMap();
        }

        /**
         * <pre>
         * 可选字段,用于扩展消息头
         * </pre>
         *
         * <code>map&lt;string, bytes&gt; attachment = 6;</code>
         */

        public com.google.protobuf.ByteString getAttachmentOrDefault(
                String key,
                com.google.protobuf.ByteString defaultValue) {
            if (key == null) {
                throw new NullPointerException();
            }
            java.util.Map<String, com.google.protobuf.ByteString> map =
                    internalGetAttachment().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <pre>
         * 可选字段,用于扩展消息头
         * </pre>
         *
         * <code>map&lt;string, bytes&gt; attachment = 6;</code>
         */

        public com.google.protobuf.ByteString getAttachmentOrThrow(
                String key) {
            if (key == null) {
                throw new NullPointerException();
            }
            java.util.Map<String, com.google.protobuf.ByteString> map =
                    internalGetAttachment().getMap();
            if (!map.containsKey(key)) {
                throw new IllegalArgumentException();
            }
            return map.get(key);
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (crcCode_ != 0) {
                output.writeInt32(1, crcCode_);
            }
            if (length_ != 0) {
                output.writeInt32(2, length_);
            }
            if (sessionId_ != 0L) {
                output.writeInt64(3, sessionId_);
            }
            if (type_ != 0) {
                output.writeInt32(4, type_);
            }
            if (priority_ != 0) {
                output.writeInt32(5, priority_);
            }
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetAttachment(),
                            AttachmentDefaultEntryHolder.defaultEntry,
                            6);
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (crcCode_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, crcCode_);
            }
            if (length_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, length_);
            }
            if (sessionId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(3, sessionId_);
            }
            if (type_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, type_);
            }
            if (priority_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(5, priority_);
            }
            for (java.util.Map.Entry<String, com.google.protobuf.ByteString> entry
                    : internalGetAttachment().getMap().entrySet()) {
                com.google.protobuf.MapEntry<String, com.google.protobuf.ByteString>
                        attachment__ = AttachmentDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(6, attachment__);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Header)) {
                return super.equals(obj);
            }
            Header other = (Header) obj;

            boolean result = true;
            result = result && (getCrcCode()
                    == other.getCrcCode());
            result = result && (getLength()
                    == other.getLength());
            result = result && (getSessionId()
                    == other.getSessionId());
            result = result && (getType()
                    == other.getType());
            result = result && (getPriority()
                    == other.getPriority());
            result = result && internalGetAttachment().equals(
                    other.internalGetAttachment());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CRCCODE_FIELD_NUMBER;
            hash = (53 * hash) + getCrcCode();
            hash = (37 * hash) + LENGTH_FIELD_NUMBER;
            hash = (53 * hash) + getLength();
            hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getSessionId());
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getType();
            hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
            hash = (53 * hash) + getPriority();
            if (!internalGetAttachment().getMap().isEmpty()) {
                hash = (37 * hash) + ATTACHMENT_FIELD_NUMBER;
                hash = (53 * hash) + internalGetAttachment().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Header parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Header parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Header parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Header parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Header parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Header parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Header parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Header parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Header parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Header parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Header parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static Header parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Header prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Header}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Header)
                HeaderOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return MessageProto.internal_static_Header_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 6:
                        return internalGetAttachment();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 6:
                        return internalGetMutableAttachment();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return MessageProto.internal_static_Header_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Header.class, Builder.class);
            }

            // Construct using com.li.proto.MessageProto.Header.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                crcCode_ = 0;

                length_ = 0;

                sessionId_ = 0L;

                type_ = 0;

                priority_ = 0;

                internalGetMutableAttachment().clear();
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return MessageProto.internal_static_Header_descriptor;
            }

            @Override
            public Header getDefaultInstanceForType() {
                return Header.getDefaultInstance();
            }

            @Override
            public Header build() {
                Header result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public Header buildPartial() {
                Header result = new Header(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.crcCode_ = crcCode_;
                result.length_ = length_;
                result.sessionId_ = sessionId_;
                result.type_ = type_;
                result.priority_ = priority_;
                result.attachment_ = internalGetAttachment();
                result.attachment_.makeImmutable();
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return (Builder) super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Header) {
                    return mergeFrom((Header) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Header other) {
                if (other == Header.getDefaultInstance()) return this;
                if (other.getCrcCode() != 0) {
                    setCrcCode(other.getCrcCode());
                }
                if (other.getLength() != 0) {
                    setLength(other.getLength());
                }
                if (other.getSessionId() != 0L) {
                    setSessionId(other.getSessionId());
                }
                if (other.getType() != 0) {
                    setType(other.getType());
                }
                if (other.getPriority() != 0) {
                    setPriority(other.getPriority());
                }
                internalGetMutableAttachment().mergeFrom(
                        other.internalGetAttachment());
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Header parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Header) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int crcCode_;

            /**
             * <pre>
             * 校验码
             * </pre>
             *
             * <code>int32 crcCode = 1;</code>
             */
            public int getCrcCode() {
                return crcCode_;
            }

            /**
             * <pre>
             * 校验码
             * </pre>
             *
             * <code>int32 crcCode = 1;</code>
             */
            public Builder setCrcCode(int value) {

                crcCode_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 校验码
             * </pre>
             *
             * <code>int32 crcCode = 1;</code>
             */
            public Builder clearCrcCode() {

                crcCode_ = 0;
                onChanged();
                return this;
            }

            private int length_;

            /**
             * <pre>
             * 消息长度(包括消息头和消息体)
             * </pre>
             *
             * <code>int32 length = 2;</code>
             */
            public int getLength() {
                return length_;
            }

            /**
             * <pre>
             * 消息长度(包括消息头和消息体)
             * </pre>
             *
             * <code>int32 length = 2;</code>
             */
            public Builder setLength(int value) {

                length_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息长度(包括消息头和消息体)
             * </pre>
             *
             * <code>int32 length = 2;</code>
             */
            public Builder clearLength() {

                length_ = 0;
                onChanged();
                return this;
            }

            private long sessionId_;

            /**
             * <pre>
             * sessionId
             * </pre>
             *
             * <code>int64 sessionId = 3;</code>
             */
            public long getSessionId() {
                return sessionId_;
            }

            /**
             * <pre>
             * sessionId
             * </pre>
             *
             * <code>int64 sessionId = 3;</code>
             */
            public Builder setSessionId(long value) {

                sessionId_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * sessionId
             * </pre>
             *
             * <code>int64 sessionId = 3;</code>
             */
            public Builder clearSessionId() {

                sessionId_ = 0L;
                onChanged();
                return this;
            }

            private int type_;

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>int32 type = 4;</code>
             */
            public int getType() {
                return type_;
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>int32 type = 4;</code>
             */
            public Builder setType(int value) {

                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息类型
             * </pre>
             *
             * <code>int32 type = 4;</code>
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            private int priority_;

            /**
             * <pre>
             * 消息优先级
             * </pre>
             *
             * <code>int32 priority = 5;</code>
             */
            public int getPriority() {
                return priority_;
            }

            /**
             * <pre>
             * 消息优先级
             * </pre>
             *
             * <code>int32 priority = 5;</code>
             */
            public Builder setPriority(int value) {

                priority_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 消息优先级
             * </pre>
             *
             * <code>int32 priority = 5;</code>
             */
            public Builder clearPriority() {

                priority_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.MapField<
                    String, com.google.protobuf.ByteString> attachment_;

            private com.google.protobuf.MapField<String, com.google.protobuf.ByteString>
            internalGetAttachment() {
                if (attachment_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            AttachmentDefaultEntryHolder.defaultEntry);
                }
                return attachment_;
            }

            private com.google.protobuf.MapField<String, com.google.protobuf.ByteString>
            internalGetMutableAttachment() {
                onChanged();
                ;
                if (attachment_ == null) {
                    attachment_ = com.google.protobuf.MapField.newMapField(
                            AttachmentDefaultEntryHolder.defaultEntry);
                }
                if (!attachment_.isMutable()) {
                    attachment_ = attachment_.copy();
                }
                return attachment_;
            }

            public int getAttachmentCount() {
                return internalGetAttachment().getMap().size();
            }

            /**
             * <pre>
             * 可选字段,用于扩展消息头
             * </pre>
             *
             * <code>map&lt;string, bytes&gt; attachment = 6;</code>
             */

            public boolean containsAttachment(
                    String key) {
                if (key == null) {
                    throw new NullPointerException();
                }
                return internalGetAttachment().getMap().containsKey(key);
            }

            /**
             * Use {@link #getAttachmentMap()} instead.
             */
            @Deprecated
            public java.util.Map<String, com.google.protobuf.ByteString> getAttachment() {
                return getAttachmentMap();
            }

            /**
             * <pre>
             * 可选字段,用于扩展消息头
             * </pre>
             *
             * <code>map&lt;string, bytes&gt; attachment = 6;</code>
             */

            public java.util.Map<String, com.google.protobuf.ByteString> getAttachmentMap() {
                return internalGetAttachment().getMap();
            }

            /**
             * <pre>
             * 可选字段,用于扩展消息头
             * </pre>
             *
             * <code>map&lt;string, bytes&gt; attachment = 6;</code>
             */

            public com.google.protobuf.ByteString getAttachmentOrDefault(
                    String key,
                    com.google.protobuf.ByteString defaultValue) {
                if (key == null) {
                    throw new NullPointerException();
                }
                java.util.Map<String, com.google.protobuf.ByteString> map =
                        internalGetAttachment().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <pre>
             * 可选字段,用于扩展消息头
             * </pre>
             *
             * <code>map&lt;string, bytes&gt; attachment = 6;</code>
             */

            public com.google.protobuf.ByteString getAttachmentOrThrow(
                    String key) {
                if (key == null) {
                    throw new NullPointerException();
                }
                java.util.Map<String, com.google.protobuf.ByteString> map =
                        internalGetAttachment().getMap();
                if (!map.containsKey(key)) {
                    throw new IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearAttachment() {
                internalGetMutableAttachment().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <pre>
             * 可选字段,用于扩展消息头
             * </pre>
             *
             * <code>map&lt;string, bytes&gt; attachment = 6;</code>
             */

            public Builder removeAttachment(
                    String key) {
                if (key == null) {
                    throw new NullPointerException();
                }
                internalGetMutableAttachment().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @Deprecated
            public java.util.Map<String, com.google.protobuf.ByteString>
            getMutableAttachment() {
                return internalGetMutableAttachment().getMutableMap();
            }

            /**
             * <pre>
             * 可选字段,用于扩展消息头
             * </pre>
             *
             * <code>map&lt;string, bytes&gt; attachment = 6;</code>
             */
            public Builder putAttachment(
                    String key,
                    com.google.protobuf.ByteString value) {
                if (key == null) {
                    throw new NullPointerException();
                }
                if (value == null) {
                    throw new NullPointerException();
                }
                internalGetMutableAttachment().getMutableMap()
                        .put(key, value);
                return this;
            }

            /**
             * <pre>
             * 可选字段,用于扩展消息头
             * </pre>
             *
             * <code>map&lt;string, bytes&gt; attachment = 6;</code>
             */

            public Builder putAllAttachment(
                    java.util.Map<String, com.google.protobuf.ByteString> values) {
                internalGetMutableAttachment().getMutableMap()
                        .putAll(values);
                return this;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Header)
        }

        // @@protoc_insertion_point(class_scope:Header)
        private static final Header DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Header();
        }

        public static Header getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Header>
                PARSER = new com.google.protobuf.AbstractParser<Header>() {
            @Override
            public Header parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Header(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Header> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Header> getParserForType() {
            return PARSER;
        }

        @Override
        public Header getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Message_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Message_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Header_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Header_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Header_AttachmentEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Header_AttachmentEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\rmessage.proto\"0\n\007Message\022\027\n\006header\030\001 \001" +
                        "(\0132\007.Header\022\014\n\004body\030\002 \001(\014\"\274\001\n\006Header\022\017\n\007" +
                        "crcCode\030\001 \001(\005\022\016\n\006length\030\002 \001(\005\022\021\n\tsession" +
                        "Id\030\003 \001(\003\022\014\n\004type\030\004 \001(\005\022\020\n\010priority\030\005 \001(\005" +
                        "\022+\n\nattachment\030\006 \003(\0132\027.Header.Attachment" +
                        "Entry\0321\n\017AttachmentEntry\022\013\n\003key\030\001 \001(\t\022\r\n" +
                        "\005value\030\002 \001(\014:\0028\001B\034\n\014com.li.protoB\014Messag" +
                        "eProtob\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_Message_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Message_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Message_descriptor,
                new String[]{"Header", "Body",});
        internal_static_Header_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_Header_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Header_descriptor,
                new String[]{"CrcCode", "Length", "SessionId", "Type", "Priority", "Attachment",});
        internal_static_Header_AttachmentEntry_descriptor =
                internal_static_Header_descriptor.getNestedTypes().get(0);
        internal_static_Header_AttachmentEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Header_AttachmentEntry_descriptor,
                new String[]{"Key", "Value",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
